### ISSUE TITLE
API Example not works

### ISSUE THREAD

**Issue by jasonfabian8** [5Society/JF_Data_Utils#22]
🐞 Problem
API not works.
System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: API_JF_Data_Utils_Example.Core.Interfaces.IStudentService Lifetime: Scoped ImplementationType: API_JF_Data_Utils_Example.Core.Services.StudentService': Unable to resolve service for type 'API_JF_Data_Utils_Example.DataAccess.Repositories.StudentRepository' while attempting to activate 'API_JF_Data_Utils_Example.Core.Services.StudentService'.)'

💡 Possible solutions
AddScoped to Services IStudentController

**Comment by jasonfabian8** [comment]
The issue was fixed with builder.Services.AddScoped<IStudentRepository, StudentRepository>();

**Comment by jasonfabian** [comment]
Bug solved
